# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kindli < Formula
  desc ""
  homepage "https://github.com/utkarsh-pro/kindli"
  version "0.0.1"
  depends_on :macos

  on_macos do
    url "https://github.com/utkarsh-pro/kindli/releases/download/v0.0.1/kindli_0.0.1_Darwin_all.tar.gz"
    sha256 "d4f838baf351b28e92a263b9ab4815d17d9667d8ba751cfd408a26dd88df5f90"

    def install
      bin.install "kindli"
    end
  end
end
