# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3cli < Formula
  desc ""
  homepage "https://github.com/utkarsh-pro/s3cli"
  version "0.0.2"

  on_macos do
    url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.2/s3cli_0.0.2_darwin_all.tar.gz"
    sha256 "2cef3ad8748d3c74da8bdf396946300096a73187b3d0652bd6c68475d7b957da"

    def install
      bin.install "s3cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.2/s3cli_0.0.2_linux_amd64.tar.gz"
      sha256 "70d0adc75771c1fa4d6435e7463a50960795f0f0999050f469c2ef544bb6d54d"

      def install
        bin.install "s3cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.2/s3cli_0.0.2_linux_arm64.tar.gz"
      sha256 "cfd37e2c3ac3653bcb53db119b4ef3b354b4bea184888aad789f4814462a1b29"

      def install
        bin.install "s3cli"
      end
    end
  end
end
