# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3cli < Formula
  desc ""
  homepage "https://github.com/utkarsh-pro/s3cli"
  version "0.0.7"

  on_macos do
    url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.7/s3cli_0.0.7_darwin_all.tar.gz"
    sha256 "b4f3312002b0677c0054a9a0b61ec66446a55a6fde85acc1d1bbfab42cb0744b"

    def install
      bin.install "s3cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.7/s3cli_0.0.7_linux_amd64.tar.gz"
      sha256 "fd8571d516859500e00c2e5ea6e5884d4156a4f576592cafbc73c3a9ff9813c4"

      def install
        bin.install "s3cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.7/s3cli_0.0.7_linux_arm64.tar.gz"
      sha256 "ca568d887eae0b917d2d286ffd9759bb34a4d9a10c83ba355ef82c0701920157"

      def install
        bin.install "s3cli"
      end
    end
  end
end
