# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3cli < Formula
  desc ""
  homepage "https://github.com/utkarsh-pro/s3cli"
  version "0.0.5"

  on_macos do
    url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.5/s3cli_0.0.5_darwin_all.tar.gz"
    sha256 "99e3ae45cf71662b21abba7cfb16dc86eec5186b0689d356134dd692ef60c047"

    def install
      bin.install "s3cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.5/s3cli_0.0.5_linux_arm64.tar.gz"
      sha256 "4dfcf6266823a9147433843e0d31072352c08b60d63ce917e51834caae8e302f"

      def install
        bin.install "s3cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utkarsh-pro/s3cli/releases/download/v0.0.5/s3cli_0.0.5_linux_amd64.tar.gz"
      sha256 "8e0742007506860cf7f8585d36c20cbe6efdd1bc820638a2e26f7a4a1559a112"

      def install
        bin.install "s3cli"
      end
    end
  end
end
