# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ucs < Formula
  desc ""
  homepage "https://github.com/utkarsh-pro/ucs"
  version "0.0.1"

  on_macos do
    url "https://github.com/utkarsh-pro/ucs/releases/download/v0.0.1/ucs_0.0.1_Darwin_all.tar.gz"
    sha256 "12bbeb2b2eabed08ce9319180b9c1280baf1f39c1b818bec327bc0ecb7dee8e2"

    def install
      bin.install "ucs"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utkarsh-pro/ucs/releases/download/v0.0.1/ucs_0.0.1_linux_arm64.tar.gz"
      sha256 "64cd27972821eb51ffde0c27bac164b1b040f0ad0b7679fa1061e8bde2002e32"

      def install
        bin.install "ucs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utkarsh-pro/ucs/releases/download/v0.0.1/ucs_0.0.1_linux_amd64.tar.gz"
      sha256 "a42133364fc5f50c4cc2f583b53ce82d28b03be3c61aaac66938ebce809cfeb9"

      def install
        bin.install "ucs"
      end
    end
  end
end
